=== 360visionn/is-a.co/schemas/domain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "domain": {
      "type": "string",
      "enum": [
        "is-a.co"
      ]
    },
    "subdomain": {
      "type": "string",
      "pattern": "^([a-z0-9_*.-]{2,64}|@)$",
      "not": {
        "enum": [
          "*",
          "ads",
          "admin",
          "cdn",
          "chat",
          "code",
          "cookie",
          "cookies",
          "copyright",
          "copyrights",
          "developer",
          "dns",
          "docs",
          "domain",
          "domains",
          "donate",
          "email",
          "ftp",
          "git",
          "help",
          "home",
          "host",
          "license",
          "mail",
          "maps",
          "market",
          "master",
          "media",
          "meet",
          "member",
          "members",
          "mobile",
          "mobiles",
          "mx",
          "my",
          "native",
          "net",
          "network",
          "now",
          "ns",
          "ns1",
          "ns2",
          "online",
          "open",
          "orig",
          "origin",
          "page",
          "pages",
          "password",
          "passwords",
          "permalink",
          "permalinks",
          "plain",
          "pop3",
          "portal",
          "portals",
          "pubs",
          "raw",
          "readme",
          "regex",
          "register",
          "registration",
          "remote",
          "rest",
          "root",
          "roots",
          "rss",
          "run",
          "script",
          "scripts",
          "secure",
          "serv",
          "server",
          "servers",
          "service",
          "services",
          "shop",
          "shops",
          "site",
          "sites",
          "smtp",
          "socket",
          "source",
          "sources",
          "ssh",
          "standard",
          "standards",
          "store",
          "stores",
          "sub",
          "subs",
          "subdomain",
          "subdomains",
          "tools",
          "vpn",
          "vps",
          "web",
          "ww",
          "ww1",
          "ww2",
          "ww3",
          "www1",
          "www2",
          "www3",
          "xml"
        ]
      }
    },
    "record": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "TXT": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          }
        },
        "A": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\\b){4}$"
          }
        },
        "AAAA": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]+|::(ffff(:0{1,4})?:)?((25[0-5]|(2[0-4]|1?[0-9])?[0-9])\\.){3}(25[0-5]|(2[0-4]|1?[0-9])?[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1?[0-9])?[0-9])\\.){3}(25[0-5]|(2[0-4]|1?[0-9])?[0-9]))$"
          }
        },
        "CNAME": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[a-z0-9_./-]{2,}$"
        },
        "NS": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z0-9._-]{3,}$"
          }
        }
      },
      "anyOf": [
        {
          "required": [
            "TXT"
          ]
        },
        {
          "required": [
            "A"
          ]
        },
        {
          "required": [
            "AAAA"
          ]
        },
        {
          "required": [
            "CNAME"
          ]
        },
        {
          "required": [
            "NS"
          ]
        }
      ]
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Path to the schema file"
    },
    "description": {
      "type": "string",
      "minLength": 4
    },
    "domain": {
      "$ref": "#/definitions/domain"
    },
    "subdomain": {
      "$ref": "#/definitions/subdomain"
    },
    "owner": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "repo": {
          "type": "string",
          "description": "Path to the github repository"
        },
        "email": {
          "type": "string",
          "description": "Email address"
        }
      }
    },
    "record": {
      "$ref": "#/definitions/record"
    },
    "proxy": {
      "type": "boolean",
      "default": true
    },
    "nested": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "subdomain": {
            "$ref": "#/definitions/subdomain"
          },
          "record": {
            "$ref": "#/definitions/record"
          },
          "proxy": {
            "type": "boolean",
            "default": true
          }
        },
        "required": [
          "subdomain",
          "record"
        ]
      }
    }
  },
  "required": [
    "$schema",
    "description",
    "domain",
    "subdomain",
    "record"
  ],
  "type": "object",
  "additionalProperties": false
}

=== 360visionn/is-a.co/domains/service/_dmarc.is-a.co.json
{
  "$schema": "../../schemas/domain.schema.json",
  "description": "DMARC record",
  "domain": "is-a.co",
  "subdomain": "_dmarc",
  "owner": {
    "repo": "https://github.com/pythonicboat/is-a.co"
  },
  "record": {
    "TXT": [
      "v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s;"
    ]
  }
}

=== 360visionn/is-a.co/domains/service/www.is-a.co.json
{
  "$schema": "../../schemas/domain.schema.json",
  "description": "www subdomain",
  "domain": "is-a.co",
  "subdomain": "www",
  "owner": {
    "repo": "https://github.com/pythonicboa/is-a.co"
  },
  "record": {
    "A": [
      "192.0.2.1"
    ],
    "AAAA": [
      "100::"
    ]
  }
}

=== 360visionn/is-a.co/domains/azurowy.is-a.co.json
{
  "$schema": "../schemas/domain.schema.json",
  "description": "Azure ADFS testing",
  "domain": "is-a.co",
  "subdomain": "azurowy",
  "owner": {
    "repo": "<https://github.com/super-admins/is-a.co.git>",
    "email": "<amo@wir.pl>"
  },
  "record": {
    "NS": ["ns1-38.azure-dns.com.", "ns2-38.azure-dns.net.", "ns3-38.azure-dns.org.", "ns4-38.azure-dns.info."]
  },
  "proxy": false 
}
